version: "3"

services:
  database: #서비스명
    restart: always
    image: mysql
    # image: mysql/mysql-server:8.0
    # image: mysql/mysql-server:5.7
    command:
      - --default-authentication-plugin=mysql_native_password #root의 default password는 "password"
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci      
#    networks:
#      - mysql-network
    #mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: book # create database named "book"
      MYSQL_ROOT_HOST: "%" #set localhost
      MYSQL_ROOT_PASSWORD: password #set password as "password" for root
      MYSQL_USER: pk8294 #create user 
      MYSQL_PASSWORD: 123 #create password for that user

    volumes:
      - ../db:/var/lib/mysql #../db에 /var/lib/mysql를 마운트함

    # docker run --name db -e MYSQL_ROOT_PASSWORD=0000 -d mysql
    # docker exec -it db bash
    # mysql -u root -p
    # 0000


  backend:
    restart: always
    build:
      context: ./book-backend #빌드는 /book-backend에
      dockerfile: Dockerfile #Dockerfile로 한다. 그리고 docker compose up --build -d로 한다. 빌드해야하니까.
    ports:
      - "8080:8080"
    links: #database와 백엔드와 통신
      - database:database
    depends_on: #db가 떠야 백엔드가 뜬다
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/book?autoReconnect=true&useSSL=false #autoReconnect=true&useSSL=false 이거 안하면 백엔드랑 디비랑 연결 안되더라
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
  frontend:
    restart: always
    build: 
      context: ./book-frontend/.
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  #backend가 먼저 떠야 frontend가 뜬다.
