import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* cn()은 여러 "className"을 합쳐주는 함수입니다. */}
      <body className={
        cn(inter.className,
           'relative h-full font-sans antialiased'
      )}>
        {/* footer가 화면 맨 밑에 고정되게끔 */}
        <main className="relative flex flex-col min-h-screen"> 
          {children}
        </main>
      </body>
    </html>
  );
}
